ALTER TABLE "ShopSettings"
  ADD COLUMN "minDeliverySubtotal" INTEGER NOT NULL DEFAULT 300000,
  ADD COLUMN "maxOrderExtraUnitPrice" INTEGER NOT NULL DEFAULT 500000,
  ADD COLUMN "maxOrderExtrasTotal" INTEGER NOT NULL DEFAULT 1000000,
  ADD COLUMN "deliveryEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "pickupEnabled" BOOLEAN NOT NULL DEFAULT true;
